### ISSUE TITLE
Normal font cannot be loaded

### ISSUE THREAD

**Issue by Tosche** [schriftgestalt/DrawBotGlyphsPlugin#1]
Since the last update, you can no longer load a normal font. The following code doesn't work, for example.
```
font('Helvetica',48)
text('Hello!',(0,0))
```

Traceback (most recent call last):
  File "<untitled>", line 1, in <module>
  File "/Users/toshi/Library/Application Support/Glyphs/Repositories/DrawBot/DrawBot.glyphsPlugin/Contents/Resources/drawBot/drawBotDrawingTools.py", line 1296, in font
    fontName = fontName.encode("ascii", "ignore")
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by schriftgestalt** [comment]
fix it.
