### ISSUE TITLE
no support for g3, pyobjc bridge error

### ISSUE THREAD

**Issue by RafalBuchner** [schriftgestalt/DrawBotGlyphsPlugin#5]
Hi, my copy of Glyphs3 app acts like it wouldn't have full pyobjc bridge installed.

I'm getting this error when trying to run open new DrawBot window and whenever I try to use drawbot as a module.
```
Traceback (most recent call last):

  File "GlyphsApp/__init__.py", line 1307, in callback_
  File "DrawBotDocument.py", line 25, in newDocument_
  File "DrawBotDocument.py", line 41, in makeWindowControllers
  File "DrawBotWindow.py", line 17, in <module>
  File "__init__.py", line 1, in <module>
  File "drawBotDrawingTools.py", line 2, in <module>

ModuleNotFoundError: No module named 'CoreText'

App:3.0.2-3046 Plugin:0.0.5-6
```

**Comment by schriftgestalt** [comment]
The DrawBot plugin is fine. This is a problem with Glyphs Python Module > https://github.com/schriftgestalt/GlyphsPythonPlugin/issues/1#issue-792515467
